services:
  doclens:
    image: doclens:${DOCLENS_IMAGE_TAG:-0.1.0-beta.1-amd64}
    container_name: doclens-x86-all-in-one
    restart: unless-stopped
    ports:
      - "10003:10003"
      - "5432:5432"
    volumes:
      - type: bind
        source: "${DOCLENS_DATA_ROOT:-/var/lib/doclens-x86}/postgresql"
        target: /var/lib/postgresql/data
        bind:
          create_host_path: true
      - type: bind
        source: "${DOCLENS_DATA_ROOT:-/var/lib/doclens-x86}/storage"
        target: /var/lib/doclens/storage
        bind:
          create_host_path: true
      - ./config:/opt/doclens/config:ro
