{{- if .Values.postgresql.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "doclens-j.postgresqlFullname" . }}
  labels:
    {{- include "doclens-j.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.postgresql.service.port }}
      targetPort: postgresql
      protocol: TCP
      name: postgresql
  selector:
    {{- include "doclens-j.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
{{- end }}
